version: "3"
services:
  php:
    build: './php/'
    container_name: PHPcontainer
    networks:
      - backend
    volumes:
      - './public_html:/var/www/html'
  apache:
    build: './apache/'
    container_name: Apachecontainer
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "85:80"
    volumes:
      - './public_html:/var/www/html'
  mysql:
    build: './mysql/'
    image: mariadb:10.5.8
    container_name: Mysqlcontainer
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - backend
    ports:
      - "3303:3306"  
    environment:
      - MYSQL_ROOT_PASSWORD=Root@123
      - MYSQL_USER= administrator
      - MYSQL_PASSWORD= admin123
      - MYSQL_ROOT_HOST= '%'
    volumes:
      - './mysql/data:/var/lib/mysql'
networks:
  frontend:
  backend: